product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
