<?php

namespace ProductBundle\Repository;

use mysql_xdevapi\Exception;
use OrderBundle\Entity\OrderItem;
use OrderBundle\Entity\ProductOrder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function actualizeOrder( ProductOrder $order )
    {
        foreach ( $order->getOrderItems() as $orderItem ) {
            $this->actualizeOrderItem($orderItem);
        }
        $this->_em->flush();
    }

    private function actualizeOrderItem( OrderItem $item )
    {
        $product = $item->getProduct();
        if ( $product->getAvailableQuantity() < $item->getQuantity() ) {
            //TODO: throw a specific exception here!
            throw new Exception('Not enough product!');
        }
        $product->setAvailableQuantity(
            $product->getAvailableQuantity()
            - $item->getQuantity()
        );
        $this->_em->persist($product);
        dump($product);
    }

}
